
MESSAGE(STATUS "Found Hello: ??")

FIND_PATH(HELLO_INCLUDE_DIR hello.h ~/tuitor_ws/cmake/step5/build/install/include/hello)
FIND_LIBRARY(HELLO_LIBRARY NAMES hello PATH ~/tuitor_ws/cmake/step5/build/install/lib)

IF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
	SET(HELLO_FOUND TRUE)
ENDIF(HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF(HELLO_FOUND)
	IF(NOT HELLO_FIND_QUIETLY)
		MESSAGE(STATUS "Found Hello: ${HELLO_LIBRARY}")
	ENDIF(HELLO_FIND_QUIETLY)
ELSE(HELLO_FOUND)
	IF(HELLO_FOUND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find hello lib")
	ENDIF(HELLO_FOUND_REQUIRED)
ENDIF(HELLO_FOUND)
